### ISSUE TITLE
how to use thrift_connector timeout and keepalive correctly

### ISSUE THREAD

**Issue by h3l** [eleme/thrift_connector#48]
I have use thriftpy as my thrifypy server and use thrift_connector as my client pool.

i have set server timeout 15 seconds like below.

```python
server = make_server(themis_thrift.Themis, ThemisRPCDispatch(), "0.0.0.0", 8001, client_timeout=15 * 1000)
```
and client pool with 5 seconds timeout and 5 seconds keepalive like below.
```python
themis_client = connection_pool.ClientPool(
    themis_thrift.Themis, "localhost",
    8001, connection_class=connection_pool.ThriftPyCyClient,
    timeout=5, keepalive=5
)
```

but when i use i got a error on rpc server like below.
```python
Traceback (most recent call last):
  File "/Users/hel/.virtualenvs/themis/lib/python2.7/site-packages/thriftpy/server.py", line 95, in handle
    self.processor.process(iprot, oprot)
  File "/Users/hel/.virtualenvs/themis/lib/python2.7/site-packages/thriftpy/thrift.py", line 295, in process
    api, seqid, result, call = self.process_in(iprot)
  File "/Users/hel/.virtualenvs/themis/lib/python2.7/site-packages/thriftpy/thrift.py", line 250, in process_in
    api, type, seqid = iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/Users/hel/.virtualenvs/themis/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 108, in read
    buff = self.sock.recv(sz)
timeout: timed out
```

i have use wireshark to capture tcp package. after 15 seconds, the rpc server have send FIN package to rpc client. But the rpc client didn't send a FIN package to server. the screenshot is below

![image](https://user-images.githubusercontent.com/1664952/31528453-e82a2470-b005-11e7-8fe6-7d4ec249f388.png)

Cound you please tell me how to use thrift_connector timeout and keepalive correctly?

**Comment by wooparadog** [comment]
Hi, the underlying cause for this is that `thrift_connector` doesn't maintain a thread to check if the connections it maintains have expired beyond `keepalive`. But it is checked when getting a connection from connection pool.

So, what you are observing is, some connections in connection pool have been idle longer than the server timeout, so server will timeout those connections. 

But those connections will be check upon use, so there shouldn't cause any failure in thrift rpc. It's better to just ignore client timeout in server, or using a lower log level (as done in `gunicorn-thrift`).
